- hosts: [MyChameleonVM2] # VM2, with no zookeeper
  remote_user:  cc    # change username depending on what it is on the cloud
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud

  tasks:
  - name: update config/server.properties for VM with zookeeper
    copy:
      src: /home/khoa/cloudcomputing/assignment2/consumer.py
      dest: /home/cc/consumer.py
