- hosts: [MyChameleonVM2] # VM2, with NO zookeeper
  remote_user:  cc    # change username depending on what it is on the cloud
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud

  tasks:
  - name: couchdb installation on vm without zookeeper
    shell: |