- hosts: [MyChameleonVMs] # both machines
  remote_user:  cc    # change username depending on what it is on the cloud
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud

  tasks:
  - name: ufw specifications
    shell: |
      sudo ufw allow 2181
      sudo ufw allow 9092
      sudo ufw allow 5984