- hosts: [MyChameleonVM1] # VM1, with zookeeper
  remote_user:  cc    # change username depending on what it is on the cloud
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud

  tasks:
  - name: Start server and zookeeper on vm1
    shell: |
      cd /home/cc/kafka_2.13-2.6.0
      bin/zookeeper-server-start.sh config/zookeeper.properties

    # bin/kafka-server-start.sh config/server.properties

      